version: '3.0'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      # - ./elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    privileged: true

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Z00a0319

  redis:
    image: redis:5.0.7
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass Z00a0319
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
#      - ./redis/data:/data
    ports:
      - "6379:6379"

  etcd:
    image: quay.io/coreos/etcd:v3.5.1
    command: etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://enjoyfood-backend-etcd:2379 --max-snapshots 10 --max-wals 10 --auto-compaction-retention=168
    ports:
      - "2379:2379"

  ubuntu_20_04:
    build:
      context: .
      dockerfile: ubuntu_20_04.Dockerfile
    volumes:
      - /Users/zhouwenzhe:/home/zhouwenzhe